<?php

namespace App\Admin\Controllers;

use App\Models\Services;
use App\Models\ServicesLocalization;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Layout\Content;
use Encore\Admin\Show;

class ServicesLocalizationController extends AdminController
{
    /**
     * Title for current resource.
     *
     * @var string
     */
    protected $title = 'App\ServicesLocalization';

    public function index(Content $content)
    {
        $content->breadcrumb(
            ['text' => 'Uslugi', 'url' => '/services'],
            ['text' => 'Uslugi Zarządzanie treścią językową']
        );
        return parent::index($content); // TODO: Change the autogenerated stub
    }
    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {

        $grid = new Grid(new ServicesLocalization());
        $grid->enableHotKeys();
        $grid->column('id', __('Id'));
        $grid->column('services_id', __('Services id'))->sortable();
        $grid->column('lang')->display(function ($lang) {

            return "<img src='/build/img/flags/24/{$lang}.png'> &nbsp;$lang</img>";

        })->sortable();
        $grid->column('title', __('Title'))->sortable();
        $grid->column('short_content', __('Short content'))->sortable();
        $grid->column('content', __('Content'))->limit(200);


        $grid->column('robots', __('Robots'))->select(config('admin.robots_list'))->help('Pokaż, czy ukryć tę treść w wyszukiwarce')->width(200)->hide();
        $grid->column('meta_title', __('Meta-Tytuł'))->help('Informacje serwisowe dla SEO');
        $grid->column('meta_descriptions', __('Meta-opis'))->help('Informacje serwisowe dla SEO');

        return $grid;
    }

    /**
     * Make a show builder.
     *
     * @param mixed $id
     * @return Show
     */
    protected function detail($id)
    {
        $show = new Show(ServicesLocalization::findOrFail($id));

        $show->field('id', __('Id'));
        $show->field('menu', __('Menu'));
        $show->field('services_id', __('Services id'));
        $show->field('lang', __('Lang'));
        $show->field('title', __('Title'));
        $show->field('short_content', __('Short content'));
        $show->field('content', __('Content'));

        $show->field('robots', __('Robots'))->select(config('admin.robots_list'))->help('Pokaż, czy ukryć tę treść w wyszukiwarce');
        $show->field('meta_title', __('Meta-Tytuł'))->help('Informacje serwisowe dla SEO');
        $show->field('meta_descriptions', __('Meta-opis'))->help('Informacje serwisowe dla SEO');
        return $show;
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        $form = new Form(new ServicesLocalization());
        $form->text('menu', __('Menu'));
        $form->text('services_id', __('Services id'))->default(request()->services_id);
        $form->select('lang', __('Lang'))->options(function ()
        {
            $arr = [];
            foreach(config('app.locales')  as  $value){
                $arr[$value] = $value;
            }
            return $arr;

        })->default(app()->getLocale());
        $form->text('title', __('Title'));
        $form->text('short_content', __('Short content'));
        $form->ckeditor('content', __('Content'));
        $form->select('robots', __('Robots'))->options(
            config('admin.robots_list')
        )->help('Pokaż, czy ukryć tę treść w wyszukiwarce');
        $form->text('meta_title', __('Meta-Tytuł'))->help('Informacje serwisowe dla SEO');
        $form->text('meta_descriptions', __('Meta-opis'))->help('Informacje serwisowe dla SEO');

        return $form;
    }
}
